# Generated by Django 5.2.8 on 2025-11-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=20)),
                ('servicio', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('DIPLOMADO', 'Diplomado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas_totales', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EJECUCION', 'En ejecución'), ('FINALIZADO', 'Finalizado')], default='PLANIFICADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRelator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_asignadas', models.PositiveIntegerField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.programa')),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.relator')),
            ],
            options={
                'unique_together': {('programa', 'relator')},
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='relatores',
            field=models.ManyToManyField(related_name='programas', through='gestion_academica.AsignacionRelator', to='gestion_academica.relator'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PREINSCRITO', 'Preinscrito'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='PREINSCRITO', max_length=20)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion_academica.participante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion_academica.programa')),
            ],
            options={
                'unique_together': {('participante', 'programa')},
            },
        ),
    ]
